services:
  web:
    build:
      context: ./
      dockerfile: ./App_Dockerfile
    container_name: cos-data-and-technology-preso-webapp-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./.app:/app
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: ./DB_Dockerfile
    container_name: cos-data-and-technology-preso-webapp-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data: