services:
  web:
    build:
      context: .
      dockerfile: ./App_Dockerfile
    container_name: cos-data-and-technology-preso-webapp-app
    ports:
      - "5000:5000"
    environment:
      POSTGRES_SERVER: db
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./DB_Dockerfile
    container_name: cos-data-and-technology-preso-webapp-db
    ports:
      - "5432:5432"